SET NAMES 'utf8';
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 血色修道院(墓地)' WHERE `entry`=45;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 死亡矿井' WHERE `entry`=78;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 暴风城监狱' WHERE `entry`=101;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 暴风城地窖' WHERE `entry`=107;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 暴风城地窖' WHERE `entry`=109;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 死亡矿井(前门)' WHERE `entry`=119;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 死亡矿井(后门)' WHERE `entry`=121;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 影牙城堡' WHERE `entry`=145;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 影牙城堡' WHERE `entry`=194;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 哀嚎洞穴' WHERE `entry`=226;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 哀嚎洞穴' WHERE `entry`=228;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 剃刀沼泽' WHERE `entry`=242;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 剃刀沼泽' WHERE `entry`=244;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑暗深渊' WHERE `entry`=257;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 黑暗深渊' WHERE `entry`=259;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 奥达曼' WHERE `entry`=286;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 奥达曼' WHERE `entry`=288;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 诺莫瑞根' WHERE `entry`=322;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 诺莫瑞根' WHERE `entry`=324;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 剃刀高地' WHERE `entry`=442;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 剃刀高地' WHERE `entry`=444;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 阿塔哈卡神庙' WHERE `entry`=446;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 阿塔哈卡神庙' WHERE `entry`=448;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 暴风城监狱' WHERE `entry`=503;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 诺莫瑞根(地铁站)' WHERE `entry`=523;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 诺莫瑞根(地铁站)' WHERE `entry`=525;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 鲁瑟兰村(泰达希尔)' WHERE `entry`=527;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 达纳苏斯(泰达希尔)' WHERE `entry`=542;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 血色修道院(墓地)' WHERE `entry`=602;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 血色修道院(大教堂)' WHERE `entry`=604;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 血色修道院(军械库)' WHERE `entry`=606;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 血色修道院(图书馆)' WHERE `entry`=608;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 血色修道院(大教堂)' WHERE `entry`=610;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 血色修道院(军械库)' WHERE `entry`=612;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 血色修道院(图书馆)' WHERE `entry`=614;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 魔法圣殿(暴风城)' WHERE `entry`=702;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 魔法圣殿(暴风城)' WHERE `entry`=704;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 奥达曼' WHERE `entry`=882;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 奥达曼' WHERE `entry`=902;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 祖尔法拉克' WHERE `entry`=922;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 祖尔法拉克' WHERE `entry`=924;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='完成 - 信仰的试练' WHERE `entry`=943;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 奥妮克希亚的巢穴' WHERE `entry`=1064;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑石深渊' WHERE `entry`=1466;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑石塔' WHERE `entry`=1468;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 黑石塔' WHERE `entry`=1470;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 黑石深渊' WHERE `entry`=1472;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 黑石塔' WHERE `entry`=2068;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 矿道地铁(铁炉堡)' WHERE `entry`=2166;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 矿道地铁(暴风城)' WHERE `entry`=2171;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 矿道地铁(暴风城)' WHERE `entry`=2173;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 矿道地铁(铁炉堡)' WHERE `entry`=2175;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 斯坦索姆(后门)' WHERE `entry`=2214;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 斯坦索姆(左门)' WHERE `entry`=2216;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 斯坦索姆(右门)' WHERE `entry`=2217;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 斯坦索姆(后门)' WHERE `entry`=2221;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 怒焰裂谷' WHERE `entry`=2226;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 怒焰裂谷' WHERE `entry`=2230;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 勇者大厅(奥格瑞玛)' WHERE `entry`=2527;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 勇者大厅(奥格瑞玛)' WHERE `entry`=2530;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 勇士大厅(暴风城)' WHERE `entry`=2532;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 勇士大厅(暴风城)' WHERE `entry`=2534;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 通灵学院' WHERE `entry`=2567;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 通灵学院' WHERE `entry`=2568;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 奥托兰克山谷(部落)' WHERE `entry`=2606;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 奥托兰克山谷(联盟)' WHERE `entry`=2608;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 奥妮克希亚的巢穴' WHERE `entry`=2848;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 熔火之心(熔火之桥)' WHERE `entry`=2886;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 熔火之心(熔火之桥)' WHERE `entry`=2890;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 玛拉顿(紫色)' WHERE `entry`=3126;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 玛拉顿(橙色)' WHERE `entry`=3131;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 玛拉顿(橙色)' WHERE `entry`=3133;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 玛拉顿(紫色)' WHERE `entry`=3134;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 厄运之槌(东正门)' WHERE `entry`=3183;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 厄运之槌(东侧门)' WHERE `entry`=3184;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 厄运之槌(东后门)' WHERE `entry`=3185;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 厄运之槌(西门左边)' WHERE `entry`=3186;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 厄运之槌(西门右边)' WHERE `entry`=3187;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 厄运之槌(北门)' WHERE `entry`=3189;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 厄运之槌(西门左边)' WHERE `entry`=3190;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 厄运之槌(西门右边)' WHERE `entry`=3191;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 厄运之槌(北门)' WHERE `entry`=3193;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 厄运之槌(东正门)' WHERE `entry`=3194;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 厄运之槌(东侧门)' WHERE `entry`=3195;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 厄运之槌(东后门)' WHERE `entry`=3196;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 厄运之槌(奥兹恩后面)' WHERE `entry`=3197;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 熔火之心(熔岩窗口)' WHERE `entry`=3528;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 熔火之心(熔岩窗口- 熔岩)' WHERE `entry`=3529;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑翼之巢' WHERE `entry`=3726;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑石塔(下层)' WHERE `entry`=3728;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 祖尔格拉布' WHERE `entry`=3928;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 祖尔格拉布' WHERE `entry`=3930;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 阿拉希盆地(联盟)' WHERE `entry`=3948;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 阿拉希盆地(部落)' WHERE `entry`=3949;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 安其拉废墟' WHERE `entry`=4006;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 安其拉废墟' WHERE `entry`=4008;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 安其拉神殿' WHERE `entry`=4010;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 安其拉神殿' WHERE `entry`=4012;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 纳克萨玛斯' WHERE `entry`=4055;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 卡拉赞(正门)' WHERE `entry`=4131;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 卡拉赞(后门)' WHERE `entry`=4135;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 破碎大厅' WHERE `entry`=4145;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 鲜血熔炉' WHERE `entry`=4147;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 玛瑟里顿的巢穴' WHERE `entry`=4149;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 地狱火壁垒' WHERE `entry`=4150;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 破碎大厅' WHERE `entry`=4151;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 鲜血熔炉' WHERE `entry`=4152;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 玛瑟里顿的巢穴' WHERE `entry`=4153;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 纳克萨玛斯' WHERE `entry`=4156;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 地狱火壁垒' WHERE `entry`=4297;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 海加尔峰(联盟营地)' WHERE `entry`=4311;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 海加尔峰(部落营地)' WHERE `entry`=4312;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 海加尔峰(暗夜精灵营地)' WHERE `entry`=4313;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 海加尔峰' WHERE `entry`=4319;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑色沼泽' WHERE `entry`=4320;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 旧希尔斯布莱德' WHERE `entry`=4321;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 黑色沼泽' WHERE `entry`=4322;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 海加尔峰' WHERE `entry`=4323;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 旧希尔斯布莱德' WHERE `entry`=4324;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑暗之门(进入外域)' WHERE `entry`=4352;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 黑暗之门(离开外域)' WHERE `entry`=4354;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 幽暗沼泽' WHERE `entry`=4363;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 蒸汽地窖' WHERE `entry`=4364;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 奴隶围栏' WHERE `entry`=4365;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 蒸汽地窖' WHERE `entry`=4366;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 幽暗沼泽' WHERE `entry`=4367;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 奴隶围栏' WHERE `entry`=4379;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 东瘟疫之地(奎尔丹纳斯岛)' WHERE `entry`=4386;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 暗影迷宫' WHERE `entry`=4397;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 塞泰克大厅' WHERE `entry`=4399;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 法力陵墓' WHERE `entry`=4401;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 奥金尼地穴' WHERE `entry`=4403;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 奥金尼地穴' WHERE `entry`=4404;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 法力陵墓' WHERE `entry`=4405;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 塞泰克大厅' WHERE `entry`=4406;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 暗影迷宫' WHERE `entry`=4407;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 东瘟疫之地(奎尔丹纳斯岛)' WHERE `entry`=4409;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 毒蛇神殿' WHERE `entry`=4416;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 毒蛇神殿' WHERE `entry`=4418;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 卡拉赞(正门)' WHERE `entry`=4436;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 禁魔监狱' WHERE `entry`=4455;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 风暴要塞' WHERE `entry`=4457;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 生态船' WHERE `entry`=4459;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 能源舰' WHERE `entry`=4461;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 生态船' WHERE `entry`=4467;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 禁魔监狱' WHERE `entry`=4468;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 能源舰' WHERE `entry`=4469;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 风暴要塞' WHERE `entry`=4470;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 海加尔峰' WHERE `entry`=4487;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 卡拉赞(后门)' WHERE `entry`=4520;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 索克雷萨之座' WHERE `entry`=4523;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 格鲁尔巢穴' WHERE `entry`=4534;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 格鲁尔巢穴' WHERE `entry`=4535;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='天灾入侵(返回点)' WHERE `entry`=4561;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='天灾入侵(返回点)' WHERE `entry`=4562;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 黑暗神庙' WHERE `entry`=4598;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 生态船' WHERE `entry`=4612;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 能源舰(后门)' WHERE `entry`=4614;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 黑暗神庙' WHERE `entry`=4619;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 祖阿曼' WHERE `entry`=4738;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 祖阿曼' WHERE `entry`=4739;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 魔导师平台' WHERE `entry`=4885;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 魔导师平台' WHERE `entry`=4887;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='进入 - 太阳之井高地' WHERE `entry`=4889;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='离开 - 太阳之井高地' WHERE `entry`=4891;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='纳格兰竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4917;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='刀锋竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4919;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='刀锋竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4921;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='刀锋竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4922;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='刀锋竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4923;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='刀锋竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4924;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='刀锋竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4925;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4927;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4928;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4929;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4930;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4931;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4932;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4933;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4934;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4935;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4936;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='洛丹伦废墟 - 传送目标 - 比赛开始' WHERE `entry`=4941;
UPDATE `locales_areatrigger_teleport` SET `Text_loc4`='刀锋竞技场 - 传送目标 - 比赛开始' WHERE `entry`=4944;
