SET NAMES 'utf8';
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=198;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=328;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=331;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=375;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=376;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=377;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=459;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=460;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=461;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=514;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=543;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=812;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=837;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=895;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=906;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=908;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=911;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=912;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=913;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=914;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=915;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=916;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=917;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=918;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=925;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=926;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=927;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=928;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=944;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=985;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=986;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=987;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=988;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=1103;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=1215;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=1218;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=1226;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=1228;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=1229;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=1231;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=1232;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=1234;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=1241;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=1292;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=1300;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=1317;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=1346;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=1355;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=1382;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=1385;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=1386;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=1404;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=1411;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=1430;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=1458;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=1470;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=1473;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=1632;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=1651;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=1676;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=1680;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=1681;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=1683;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=1699;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=1700;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=1701;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=1702;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=1703;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=1901;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=2114;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=2119;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=2122;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=2123;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=2124;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=2126;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=2127;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=2128;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=2129;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=2130;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=2131;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=2132;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=2326;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=2327;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=2329;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=2367;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=2390;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=2391;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=2399;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=2485;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=2489;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=2492;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=2627;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=2704;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=2798;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=2818;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=2834;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=2836;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=2837;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=2855;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=2856;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=2878;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=2879;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=2998;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=3001;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=3004;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=3007;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=3009;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=3011;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=3013;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=3026;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=3028;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3030;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3031;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3032;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=3033;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=3034;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=3036;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3038;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3039;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3040;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3041;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3042;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3043;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=3044;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=3045;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=3046;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=3047;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=3048;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=3049;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3059;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=3060;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3061;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3062;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3063;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=3064;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3065;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3066;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=3067;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=3069;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=3087;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=3136;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=3137;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3153;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3154;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=3155;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=3156;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3157;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3169;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=3170;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3171;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=3172;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3173;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=3174;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=3175;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=3179;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=3181;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=3184;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=3185;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=3290;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=3306;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=3324;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=3325;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=3326;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=3327;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=3328;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=3332;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3344;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=3345;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=3347;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3352;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3353;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3354;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=3355;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=3357;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=3363;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=3365;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=3373;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=3399;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=3401;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=3403;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=3404;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3406;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3407;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3408;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=3478;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=3484;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=3494;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=3523;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=3545;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=3549;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=3555;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=3557;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3593;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=3594;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=3595;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3596;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=3597;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=3598;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=3599;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=3600;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3601;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=3602;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=3603;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=3604;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=3605;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=3606;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=3607;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=3620;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=3622;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=3624;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=3688;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=3690;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=3698;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=3703;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=3704;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=3706;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=3707;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=3963;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=3964;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=3965;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=3967;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=4087;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=4089;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=4090;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=4091;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=4092;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=4138;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=4146;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=4156;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=4159;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=4160;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=4163;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=4165;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=4193;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=4204;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=4205;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=4210;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=4211;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=4212;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=4213;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=4214;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=4215;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=4217;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=4218;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=4219;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=4254;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=4258;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=4320;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=4552;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=4563;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=4564;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=4565;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=4566;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=4567;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=4568;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=4573;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=4576;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=4578;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=4582;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=4583;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=4584;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=4588;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=4591;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=4593;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=4594;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=4595;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=4596;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=4598;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=4606;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=4607;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=4608;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=4611;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=4614;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=4616;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=4732;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=4752;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=4753;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=4772;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=4773;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=4898;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=4900;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=5032;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=5037;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=5038;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=5040;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=5041;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=5113;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=5114;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=5115;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=5116;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=5117;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=5127;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=5137;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=5141;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=5142;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=5143;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5144;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5145;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5146;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=5147;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=5148;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=5149;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=5150;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=5153;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=5157;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=5159;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=5161;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=5164;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=5165;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=5166;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=5167;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=5171;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=5172;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=5173;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=5174;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=5177;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=5392;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=5479;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=5480;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=5482;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=5484;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=5489;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=5491;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=5492;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=5493;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=5495;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=5496;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5497;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5498;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=5499;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=5501;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=5502;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=5504;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=5505;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=5506;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=5511;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=5513;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=5515;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=5516;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=5517;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=5518;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=5564;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=5566;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=5612;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=5690;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=5695;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=5759;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=5784;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5880;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5882;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5883;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5884;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=5885;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=5938;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=5939;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=5941;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=5943;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=5957;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=5958;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=5994;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=6014;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=6018;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=6094;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=6251;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=6286;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6287;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6288;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6289;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6290;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6291;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6292;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6295;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=6297;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=6299;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6306;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=6387;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=6707;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=7087;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=7088;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=7089;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=7230;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=7231;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=7232;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=7311;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=7312;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=7315;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=7406;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings! Can I teach you how to turn beast hides into armor?' WHERE `entry`=7866;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings! Can I teach you how to turn beast hides into armor?' WHERE `entry`=7867;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings! Can I teach you how to turn beast hides into armor?' WHERE `entry`=7868;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings! Can I teach you how to turn beast hides into armor?' WHERE `entry`=7869;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings! Can I teach you how to turn beast hides into armor?' WHERE `entry`=7870;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings! Can I teach you how to turn beast hides into armor?' WHERE `entry`=7871;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=7944;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=7946;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=7948;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=7949;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=7953;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=7954;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=8126;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=8128;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=8140;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=8141;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=8142;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=8144;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=8146;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=8153;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=8306;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=8308;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=8736;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=8738;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=9465;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=9584;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=10086;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=10088;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=10089;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=10090;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=10930;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=10993;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=11017;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=11025;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=11031;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=11037;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=11048;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=11050;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=11051;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=11052;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=11072;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=11073;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=11074;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=11097;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=11098;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=11146;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=11177;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=11178;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=11397;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=11401;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=11406;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=11557;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=11865;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=11866;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=11867;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=11868;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=11869;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=11870;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=12025;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=12030;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=12032;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=12042;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=12961;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=13084;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=13283;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=13417;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=14740;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=15279;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=15280;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=15283;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=15284;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=15285;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=15400;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=15501;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=15513;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=16000;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=16160;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=16161;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=16190;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=16253;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=16265;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=16266;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=16269;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=16270;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=16271;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=16272;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=16273;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=16275;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=16276;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=16277;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=16278;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=16279;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=16280;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=16366;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=16367;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=16499;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=16500;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=16501;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=16502;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=16503;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=16583;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=16588;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=16621;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=16633;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=16639;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=16640;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=16642;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=16644;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=16646;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=16647;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=16648;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=16651;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=16652;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=16653;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=16654;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=16655;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=16658;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=16659;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=16660;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=16662;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=16663;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=16667;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=16669;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=16672;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=16673;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=16674;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=16675;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=16676;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=16679;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=16680;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=16681;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=16684;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=16685;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=16686;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=16688;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=16692;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=16702;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=16712;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=16719;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=16721;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=16723;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=16724;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=16725;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=16726;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=16727;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=16728;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=16729;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=16731;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=16736;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=16738;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=16744;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=16746;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=16749;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=16752;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=16755;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=16756;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=16761;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=16763;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=16771;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=16773;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=16774;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=16780;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=16823;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=17005;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=17089;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=17101;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=17110;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=17120;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=17121;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=17122;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=17204;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=17212;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=17214;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=17215;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=17219;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=17222;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=17245;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=17246;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=17424;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=17434;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=17441;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=17442;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=17480;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=17481;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=17482;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=17483;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='' WHERE `entry`=17484;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=17487;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=17488;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=17504;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=17505;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=17509;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=17510;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=17511;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=17513;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=17514;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=17519;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=17520;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=17634;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=17637;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=17844;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=17983;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='I can teach you how to use a fishing pole to catch fish.' WHERE `entry`=18018;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=18747;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=18748;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=18749;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=18751;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=18752;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=18753;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=18754;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=18755;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=18771;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn found cloth into cloth armor?' WHERE `entry`=18772;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=18773;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=18774;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=18775;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Searching for herbs requires both knowledge and instinct.' WHERE `entry`=18776;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=18777;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=18779;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=18802;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='You have not lived until you have dug deep into the earth.' WHERE `entry`=18804;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=18987;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=18988;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=18990;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=18991;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=18993;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='With alchemy you can turn found herbs into healing and other types of potions.' WHERE `entry`=19052;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=19063;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='It requires a steady hand to remove the leather from a slain beast.' WHERE `entry`=19180;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=19184;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=19185;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=19186;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=19187;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=19251;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=19252;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=19340;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=19341;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Can I teach you how to turn the meat you find on beasts into a feast?' WHERE `entry`=19369;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=19478;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=19539;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Enchanting is the art of improving existing items through magic. ' WHERE `entry`=19540;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=19576;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=19774;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=19775;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=19777;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to cut preecious gems and craft jewelry?' WHERE `entry`=19778;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=20124;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Care to learn how to turn the ore that you find into weapons and metal armor?' WHERE `entry`=20125;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=20406;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=20407;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=20500;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=20511;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=20791;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Hello!  Can I teach you something?' WHERE `entry`=20914;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Greetings!  Can I teach you how to turn beast hides into armor?' WHERE `entry`=21087;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Here, let me show you how to bind those wounds....' WHERE `entry`=22477;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=23103;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=23127;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=23128;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=23534;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=24868;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='Engineering is very simple once you grasp the basics.' WHERE `entry`=25099;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，德鲁伊！ 准备好接受训练了吗？' WHERE `entry`=26324;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，猎人！ 准备好接受训练了吗？' WHERE `entry`=26325;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=26326;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，圣骑士！ 准备好接受训练了吗？' WHERE `entry`=26327;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，牧师！ 准备好接受训练了吗？' WHERE `entry`=26328;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，盗贼！ 准备好接受训练了吗？' WHERE `entry`=26329;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，萨满祭司！ 准备好接受训练了吗？' WHERE `entry`=26330;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，术士！ 准备好接受训练了吗？' WHERE `entry`=26331;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，战士！ 准备好接受训练了吗？' WHERE `entry`=26332;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=27703;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='你好，法师！ 准备好接受训练了吗？' WHERE `entry`=27704;
UPDATE `locales_trainer_greeting` SET `Text_loc4`='欢迎光临！' WHERE `entry`=27705;
